In [1]:
import pandas as pd

In [2]:
data_preprocess = pd.read_csv('Datapreprocessing data.csv')

In [42]:
X = data_preprocess.iloc[:,:-1].values #all the values expect last target column selected

In [43]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [9]:
Y = data_preprocess.iloc[:,-1].values #last column

In [10]:
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [11]:
#handle missing values

In [17]:
data_preprocess.isnull().values.any() #Check if data has any missing values

True

In [18]:
data_preprocess

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [13]:
#Nan values are the missing values

In [44]:
from sklearn.preprocessing import Imputer  #this library contains methods and functions for preprocessing the data

In [45]:
imputer = Imputer(missing_values = 'NaN', strategy = 'mean', axis=0) #taking mean of column values and putting it in Nan values 

C:\Users\00821554\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [46]:
imputer

Imputer(axis=0, copy=True, missing_values='NaN', strategy='mean', verbose=0)

In [47]:
imputer = imputer.fit(X[:,1:3]) #fitting object imputer to column 1 and 2 of X

In [48]:
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [49]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [50]:
#Encode categorical data

In [51]:
from sklearn.preprocessing import LabelEncoder

In [52]:
labelencoder_X = LabelEncoder()

In [53]:
X[:,0] = labelencoder_X.fit_transform(X[:,0])

In [54]:
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [55]:
#but then here 2>1 and 1>0 which we don't want hence the dummy variables

In [56]:
from sklearn.preprocessing import OneHotEncoder

In [57]:
onehotencoder = OneHotEncoder(categorical_features = [0]) #giving column number 0

In [58]:
onehotencoder

OneHotEncoder(categorical_features=[0], categories=None,
       dtype=<class 'numpy.float64'>, handle_unknown='error',
       n_values=None, sparse=True)

In [59]:
X = onehotencoder.fit_transform(X).toarray()

C:\Users\00821554\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\00821554\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [64]:
X

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        5.40000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04]])

In [74]:
pd.options.display.float_format = '{:.0f}'.format

In [75]:
pd.DataFrame(X[:,0:3]) #see dummy columns 

0  1  2
0  1  0  0
1  0  0  1
2  0  1  0
3  0  0  1
4  0  1  0
5  1  0  0
6  0  0  1
7  1  0  0
8  0  1  0
9  1  0  0

In [76]:
labelencoder_y = LabelEncoder()

In [77]:
Y = labelencoder_y.fit_transform(Y)

In [79]:
Y #0 is encoded to No and 1 to Yes

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [80]:
#Splitting dataset into training and test set

In [81]:
from sklearn.model_selection import train_test_split

In [82]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 121)

In [83]:
#Feature Scaling

In [86]:
#Because distance between any two salary values will dominate distance between any two age values. 
#Hence we need to scale
#Options - Standardization and Normalization

In [87]:
from sklearn.preprocessing import StandardScaler

In [89]:
sc_X = StandardScaler()

In [91]:
X_train = sc_X.fit_transform(X_train)

In [92]:
X_test = sc_X.transform(X_test) #since we have already fitted method on train dataset you just need transform function on test

In [93]:
X_train

array([[ 1.29099445, -0.57735027, -0.77459667,  1.61165483,  1.84874777],
       [-0.77459667, -0.57735027,  1.29099445,  0.06240052,  0.00284861],
       [-0.77459667, -0.57735027,  1.29099445,  0.18289808, -0.92010097],
       [-0.77459667, -0.57735027,  1.29099445, -1.64177922, -1.33030078],
       [-0.77459667,  1.73205081, -0.77459667,  0.37225138,  0.28770959],
       [ 1.29099445, -0.57735027, -0.77459667,  0.9919531 ,  1.13089809],
       [ 1.29099445, -0.57735027, -0.77459667, -0.40237577, -0.30480125],
       [-0.77459667,  1.73205081, -0.77459667, -1.17700292, -0.71500106]])

In [94]:
X_test

array([[-0.77459667,  1.73205081, -0.77459667,  1.92150569,  2.25894758],
       [ 1.29099445, -0.57735027, -0.77459667, -0.09252491,  0.61814833]])

In [95]:
#Do we need any to apply feature scaling to Y, since it had only 2 categories 0 and 1?

In [96]:
#No because this is a classification problem with just 2 categories